define([], function () {
    return {
        "PropertyPaneDescription": "Beskrivelse",
        "BasicGroupName": "Gruppenavn",
        "DescriptionFieldLabel": "Beskrivelsesfelt",
        "SiteURLLabel": "Skriv URL'en for den webside med listen",
        "SiteURLDescription": "Hvis ingen URL er givet, så vil listen blive hentet fra den nuværende side",
        "MeetingsListOption": "Vælg en liste til Møder",
        "MeetingRegistrationListOption": "Vælg en liste til Mødetilmeldinger",
        "Register": "Deltag",
        "ChooseCategory": "Vælg kategori",
        "ChooseMeeting": "Vælg mødetype ",
        "ChooseMeetingLabel": "Mødetype:",
        "ChooseCategoryLabel": "Kategori:",
        "ChooseRoomLabel": "Lokale:",
        "ChooseRoom": "Vælg lokale",
        "Yes": "Ja",
        "No": "Nej",
        "ShowMyRegistrations": "Vis mine møder:",
        "AddEvent": "Tilføj begivenhed",
        "Unregister": "Deltag ikke",
        "All": "Alle",
        "MeetingManagementHeader": "Mødehåndtering",
        "StartDateAndTime": "Startdato og tidspunkt",
        "EndDateAndTime": "Slutter",
        "Room": "Lokale",
        "Category": "Kategori",
        "MeetingType": "Mødetype",
        "Registrations": "Deltagere",
        "RegisteredUsers": "Brugere der deltager",
        "ShowRegistrationsLabel": "Vis deltagere",
        "RegisterOptionsLabel": "Vis deltag / deltag ikke",
        "ShowInView": "Vis kun i oversigtsvisning",
        "ShowInEvent": "Vis kun i begivenhed",
        "ShowBoth": "Vis begge steder",
        "Hide": "Vis slet ikke",
        "Close": "Luk",
        "ContentSettingsGroupName": "Indhold",
        "DetailsSettingsGroupName": "Detaljer",
        "toggleOn": "Til",
        "toggleOff": "Fra",
        "NextPage": "Næste side",
        "GoBack": "Gå tilbage",
        "DownloadICal": "Hent",
        "ShowPagiationLabel": "Vis paginering",
        "NumberOfMeetings": "Antal møder",
        "Layout": "Layout",
        "enforceLanguage": "Gennemtving sprog",
        "SeeAllUrlLabel": "Skriv URL 'Se alle' skal henvise til",
        "FilterById": "Filtrer ud fra ID",
        "DateAndTime": "Dato og tidspunkt",
        "RegistrationDeadline": "Tilmeldingsfrist",
        "Help": "Hjælp",
        "FilterByMeetingType": "Filtrer efter mødetype",
        "FilterByCategory": "Filtrer efter kategori",
        "FilterByRoom": "Filtrer efter lokale",
        "HideRegistrations": "Skjul deltagere",
        "ShowRegistrations": "Vis deltagere",
        "OK": "OK",
        "Confirmation": "Bekræftelse",
        "ConfirmationLabel": "Jeg bekræfter, at jeg har fået den rette godkendelse",
        "Success": "Succes",
        "Cancel": "Annuller",
        "Confirm": "Bekræft",
        "MessageConfirmMeeting": "Er du sikker på, at du vil deltage i dette møde?",
        "ApprovalMessage": "OBS! Dette møde kræver godkendelse. Bekræft venligst, at du har den rette godkendelse for at fortsætte.",
        "MessageUnregisterMeeting": "Er du sikker på, at du vil afmelde dig fra dette møde?",
        "Registered": "Du er nu tilmeldt!",
        "Unregistered": "Du er nu afmeldt mødet.",
        "SeeAll": "Se alle",
        "ShowUserMenuLabel": "Vis brugermenu",




    }
});