define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "SiteURLLabel": "Type the URL for webpage containing the list",
    "SiteURLDescription": "If no URL is given, the lists will be collected from the current site",
    "MeetingsListOption": "Choose a list for Meetings",
    "MeetingRegistrationListOption": "Choose a list for Meeting Registrations",
    "Register": "Register",
    "ChooseCategory": "Choose category",
    "ChooseMeeting": "Choose meting",
    "ChooseMeetingLabel": "Filter by meeting:", 
    "ChooseCategoryLabel": "Filter by category:",
    "ChooseRoomLabel": "Filter by room:",
    "ChooseRoom": "Choose room",
    "Yes": "Yes",
    "No": "No",
    "ShowMyRegistrations": "Show my registrations",
    "AddEvent": "Add event",
    "Unregister": "Unregister",
    "All": "All",
    "MeetingManagementHeader": "Meeting Management",
    "StartDateAndTime": "Start date and time",
    "EndDateAndTime": "Ends",
    "Room": "Room",
    "Category": "Category",
    "MeetingType": "MeetingType",
    "Registrations": "Registrations",
    "RegisteredUsers": "Registrated users",
    "ShowRegistrationsLabel": "Show registrations",
    "RegisterOptionsLabel": "Show register / unregister",
    "ShowInView": "Show only in view",
    "ShowInEvent": "Show only in event",
    "ShowBoth": "Show both in view and event",
    "Hide": "Hide",
    "Close": "Close",
    "ContentSettingsGroupName": "Content",
    "DetailsSettingsGroupName": "Details",
    "ToggleOn": "On",
    "ToggleOff": "Off",
    "NextPage": "Next page",
    "GoBack": "Go back",
    "DownloadICal": "Download",
    "ShowPagiationLabel": "Show pagination",
    "NumberOfMeetings": "Number of meetings",
    "Layout": "Layout",
    "enforceLanguage": "Enforce language",
    "SeeAllUrlLabel": "Type the URL 'Se all' should point to",
    "FilterById": "Filter by Meeting ID",
    "DateAndTime": "Date and time",
    "RegistrationDeadline": "Registration deadline",
    "Help": "Help",
    "FilterByMeetingType": "Filter by meeting type",
    "FilterByCategory": "Filter by category",
    "FilterByRoom": "Filter by room",
    "HideRegistrations": "Hide registrations",
    "ShowRegistrations": "Show registrations",
    "OK": "OK",
    "Confirmation": "Confirmation",
    "ConfirmationLabel": "I confirm I have the required approval",
    "Success": "Success",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "MessageConfirmMeeting": "Are you sure you want to register for this meeting?",
    "ApprovalMessage": "OBS! This meeting requires approval. Please confirm you have approval to proceed.",
    "MessageUnregisterMeeting": "Are you sure you want to unregister from this meeting?",
    "Registered": "You are now registered!",
    "Unregistered": "Unregistered from meeting.",
    "SeeAll": "See all",
    "ShowUserMenuLabel": "Show user menu",



  }
});