declare interface IMeetingManagementWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  SiteURLLabel: string;
  SiteURLDescription: string;
  MeetingsListOption: string;
  MeetingRegistrationListOption: string;
  ModuleHeader: string;
  Register: string;
  Unregister: string;
  ChooseMeeting: string;
  ChooseCategory: string;
  ChooseMeetingLabel: string;
  ChooseCategoryLabel: string;
  ChooseRoomLabel: string;
  ChooseRoom: string;
  Yes: string;
  No: string;
  ShowMyRegistrations: string;
  AddEvent: string;
  All: string;
  MeetingManagementHeader: string;
  StartDateAndTime: string;
  EndDateAndTime: string;
  Room: string;
  Category: string;
  MeetingType: string;
  Registrations: string;
  RegisteredUsers: string;
  ShowRegistrationsLabel: string;
  RegisterOptionsLabel: string;
  ShowInView: string;
  ShowInEvent: string;
  ShowBoth: string;
  Hide: string;
  Close: string;
  ContentSettingsGroupName: string;
  DetailsSettingsGroupName: string;
  ToggleOn: string;
  ToggleOff: string;
  NextPage: string;
  GoBack: string;
  DownloadICal: string;
  ShowPagiationLabel: string;
  NumberOfMeetings: string;
  Layout: string;
  enforceLanguage: string;
  SeeAllUrlLabel: string;
  FilterById: string;
  DateAndTime: string;
  RegistrationDeadline: string;
  Help: string;
  FilterByMeetingType: string;
  FilterByCategory: string;
  FilterByRoom: string;
  HideRegistrations: string;
  ShowRegistrations: string;
  OK: string;
  Confirmation: string;
  ConfirmationLabel: string;
  Success: string;
  Cancel: string;
  Confirm: string;
  MessageConfirmMeeting: string;
  ApprovalMessage: string;
  MessageUnregisterMeeting: string;
  Registered: string;
  Unregistered: string;
  SeeAll: string;
  ShowUserMenuLabel: string;
}

declare module 'MeetingManagementWebPartStrings' {
  const strings: IMeetingManagementWebPartStrings;
  export = strings;
}
